"use client";
import { useEffect, useState } from "react";
import { useInfiniteQuery, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDownLeft, ArrowUpRight, ChevronRight, CircleCheck, Clock3, LayoutGrid, ListFilter, LogOut, Plus, Search, Users, Wallet, X } from "lucide-react";
import { api, ApiError, dateLabel, money, type Commitment, type Contact, type Dashboard, type Page, type Profile, type Transaction } from "@/lib/api";
import { AuthScreen } from "@/features/auth/auth-screen";
import { CommitmentForm, ContactForm, PaymentForm } from "@/features/commitments/forms";
import { Dialog } from "@/components/dialog";

function ErrorNotice({ error, retry }: { error: Error; retry: () => void }) {
  return <div role="alert" className="error-box">{error.message} <button className="text-button" onClick={retry}>Reintentar</button></div>;
}

export default function Home() {
  const client = useQueryClient();
  const profile = useQuery({ queryKey: ["me"], queryFn: () => api<Profile>("/me"), staleTime: 60000 });
  useEffect(() => {
    const expire = () => { client.removeQueries({ predicate: query => query.queryKey[0] !== "me" }); client.setQueryData(["me"], null); };
    window.addEventListener("nomi-session-expired", expire);
    return () => window.removeEventListener("nomi-session-expired", expire);
  }, [client]);
  if (profile.isPending) return <main className="loading-screen"><span className="brand">nomi.</span><p role="status">Preparando tu espacio…</p></main>;
  if (profile.error && !(profile.error instanceof ApiError && profile.error.status === 401)) return <main className="loading-screen"><h1>Tu espacio estará aquí.</h1><ErrorNotice error={profile.error} retry={() => profile.refetch()} /></main>;
  if (!profile.data) return <AuthScreen onSuccess={value => { client.removeQueries({ predicate: query => query.queryKey[0] !== "me" }); client.setQueryData(["me"], value); }} />;
  return <Workspace key={profile.data.workspace.id} profile={profile.data} />;
}

function Workspace({ profile }: { profile: Profile }) {
  const client = useQueryClient();
  const [section, setSection] = useState("Resumen");
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [modal, setModal] = useState<"commitment" | "contact" | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [toast, setToast] = useState("");
  const [logoutError, setLogoutError] = useState("");
  const contactsQuery = useInfiniteQuery({ queryKey: ["contacts"], initialPageParam: "", queryFn: ({ pageParam }) => api<Page<Contact>>(`/contacts?limit=100${pageParam ? `&cursor=${pageParam}` : ""}`), getNextPageParam: page => page.next_cursor ?? undefined });
  const contacts = contactsQuery.data?.pages.flatMap(p => p.items) ?? [];
  const commitmentsQuery = useInfiniteQuery({ queryKey: ["commitments"], initialPageParam: "", queryFn: ({ pageParam }) => api<Page<Commitment>>(`/commitments?limit=30${pageParam ? `&cursor=${pageParam}` : ""}`), getNextPageParam: page => page.next_cursor ?? undefined });
  const summary = useQuery({ queryKey: ["dashboard"], queryFn: () => api<Dashboard>("/dashboard/summary") });
  const commitments = commitmentsQuery.data?.pages.flatMap(p => p.items) ?? [];
  const names = new Map(contacts.map(c => [c.id, c.name]));
  const filtered = commitments.filter(c => (filter === "all" || c.direction === filter || (filter === "overdue" && c.timing_state === "overdue")) && `${c.concept ?? ""} ${names.get(c.contact_id) ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(""), 5000); return () => clearTimeout(timer); } }, [toast]);
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ["commitments"] }), client.invalidateQueries({ queryKey: ["dashboard"] }), client.invalidateQueries({ queryKey: ["detail"] }), client.invalidateQueries({ queryKey: ["history"] })]); };
  async function contactCreated(contact: Contact) {
    client.setQueryData(["contacts"], (old: { pages: Page<Contact>[]; pageParams: string[] } | undefined) => ({ pages: old ? [{ ...old.pages[0], items: [...old.pages[0].items, contact] }, ...old.pages.slice(1)] : [{ items: [contact], next_cursor: null }], pageParams: old?.pageParams ?? [""] }));
  }
  return <div className="workspace">
    <aside className="sidebar"><a href="/" className="brand"><span className="brand-mark">n</span>nomi<span className="brand-dot">.</span></a><div className="space-label">TU ESPACIO PERSONAL</div><nav aria-label="Navegación principal">{[["Resumen", LayoutGrid], ["Pendientes", Wallet], ["Contactos", Users]].map(([label, Icon]) => { const ItemIcon = Icon as typeof Wallet; return <button key={label as string} className={section === label ? "nav-item active" : "nav-item"} onClick={() => setSection(label as string)}><ItemIcon size={19} />{label as string}{label === "Pendientes" && <span className="nav-count">{summary.data?.active_commitments ?? "—"}</span>}</button>; })}</nav><div className="sidebar-note"><span className="note-spark">✳</span><strong>Un pendiente menos.<br />Un poco más de calma.</strong><p>Todo lo que necesitas para tener las cuentas claras.</p></div><div className="user-block"><span className="avatar">{profile.user.display_name.slice(0, 1).toUpperCase()}</span><div><strong>{profile.user.display_name}</strong><small>Mi espacio · MXN</small></div><button title="Cerrar sesión" aria-label="Cerrar sesión" className="icon-button" onClick={async () => { try { await api("/auth/logout", {}); client.removeQueries({ predicate: query => query.queryKey[0] !== "me" }); client.setQueryData(["me"], null); } catch (e) { setLogoutError((e as Error).message); } }}><LogOut size={17} /></button></div></aside>
    <main className="main-content"><header className="topbar"><span>Mi espacio <ChevronRight size={14} /><strong>{section}</strong></span><span className="topbar-right"><span className="status-dot" /> Tu espacio personal</span></header>
      <div className="page-content"><div className="page-heading"><div><span className="eyebrow">{new Intl.DateTimeFormat("es-MX", { weekday: "long", day: "numeric", month: "long", timeZone: profile.workspace.timezone }).format(new Date())}</span><h1>{section === "Resumen" ? `Hola, ${profile.user.display_name.split(" ")[0]}.` : section === "Pendientes" ? "Tus pendientes." : "Tus contactos."}</h1><p className="muted">{section === "Resumen" ? "Un vistazo a tus pendientes. Y a lo que sigue." : section === "Pendientes" ? "Cada compromiso, cada abono. Todo en orden." : "Las personas y negocios con quienes llevas tus cuentas."}</p></div><button className="primary" onClick={() => setModal(section === "Contactos" ? "contact" : "commitment")}><Plus size={18} />{section === "Contactos" ? "Nuevo contacto" : "Registrar pendiente"}</button></div>
      {logoutError && <p className="error-box" role="alert">{logoutError}</p>}
      {section === "Resumen" && <>{summary.error ? <ErrorNotice error={summary.error} retry={() => summary.refetch()} /> : <div className="stats-grid"><div className="stat-card hero-stat"><div className="stat-label"><span>Me deben</span><ArrowDownLeft size={20} /></div><strong>{summary.data ? money(summary.data.receivable_balance_minor) : "…"}</strong><div className="stat-bottom">Por cobrar <span>MXN</span></div><div className="hero-orbit" /></div><div className="stat-card"><div className="stat-label"><span>Yo debo</span><ArrowUpRight size={20} /></div><strong>{summary.data ? money(summary.data.payable_balance_minor) : "…"}</strong><div className="stat-bottom">Por pagar <span>MXN</span></div></div><div className="stat-card"><div className="stat-label"><span>Vencido</span><Clock3 size={20} className="orange" /></div><strong>{summary.data ? money(summary.data.overdue_balance_minor) : "…"}</strong><div className="stat-bottom">Requiere atención <span className="tiny-dot orange-bg" /></div></div><div className="stat-card"><div className="stat-label"><span>Por vencer</span><ListFilter size={20} /></div><strong>{summary.data ? money(summary.data.due_soon_balance_minor) : "…"}</strong><div className="stat-bottom">Hoy y próximos 7 días</div></div></div>}
      <div className="calm-banner"><span className="calm-icon"><CircleCheck size={20} /></span><div><strong>{summary.data?.overdue_balance_minor ? "Un buen momento para dar seguimiento." : "Un espacio para tener claridad."}</strong><span>{summary.data?.overdue_balance_minor ? "Revisa tus pendientes vencidos y consulta su historial." : "Cada abono queda registrado para que siempre sepas cómo va tu saldo."}</span></div><button className="text-button" onClick={() => { setSection("Pendientes"); setFilter(summary.data?.overdue_balance_minor ? "overdue" : "all"); }}>Ver pendientes <ArrowUpRight size={16} /></button></div></>}
      {section !== "Contactos" ? <section className="list-panel"><div className="panel-title"><div><h2>{section === "Resumen" ? "Tus pendientes" : "Todos tus pendientes"}</h2><span>{summary.data?.active_commitments ?? "—"} activos en tu espacio</span></div><label className="search-field"><Search size={17} /><input aria-label="Buscar en pendientes cargados" value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar en esta lista" /></label></div><div className="filter-tabs" aria-label="Filtrar pendientes">{[["all", "Todos"], ["receivable", "Me deben"], ["payable", "Yo debo"], ["overdue", "Vencidos"]].map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={filter === value ? "selected" : ""}>{label}</button>)}</div>
        {commitmentsQuery.isPending ? <p className="panel-message" role="status">Cargando tus pendientes…</p> : commitmentsQuery.error ? <ErrorNotice error={commitmentsQuery.error} retry={() => commitmentsQuery.refetch()} /> : filtered.length ? <div className="commitment-list"><div className="list-columns"><span>CONTACTO / CONCEPTO</span><span>VENCIMIENTO</span><span>ESTADO</span><span>PENDIENTE</span><span /></div>{filtered.map(c => <button className="commitment-row" key={c.id} onClick={() => setSelected(c.id)}><span className="contact-cell"><span className={`contact-avatar ${c.direction === "payable" ? "sand" : ""}`}>{(names.get(c.contact_id) ?? "C").slice(0, 1)}</span><span><strong>{names.get(c.contact_id) ?? "Contacto"}</strong><small>{c.concept || (c.direction === "receivable" ? "Dinero por cobrar" : "Dinero por pagar")}</small></span></span><span className="due-cell">{dateLabel(c.due_date)}</span><span className={`badge ${c.lifecycle_status === "paid" ? "paid" : c.timing_state === "overdue" ? "overdue" : ""}`}>{c.lifecycle_status === "paid" ? "Pagado" : c.timing_state === "overdue" ? "Vencido" : c.payment_state === "partial" ? "Abonado" : "Pendiente"}</span><span className="amount-cell"><strong>{money(c.balance_minor)}</strong><small>{c.direction === "receivable" ? "Me deben" : "Yo debo"}</small></span><ChevronRight size={17} /></button>)}</div> : <div className="empty-state"><span className="empty-icon"><Wallet size={30} strokeWidth={1.3} /></span><h3>{commitments.length ? "No hay coincidencias." : "Tu primer pendiente, en su lugar."}</h3><p>{commitments.length ? "Prueba otro filtro o carga más pendientes." : "Registra algo que te deban o tengas por pagar. El saldo y los abonos se quedan aquí."}</p><button className="secondary" onClick={() => setModal("commitment")}><Plus size={17} />Registrar pendiente</button></div>}
        {commitmentsQuery.hasNextPage && <button className="load-more" disabled={commitmentsQuery.isFetchingNextPage} onClick={() => commitmentsQuery.fetchNextPage()}>Cargar más pendientes</button>}
        <div className="panel-footer"><span><span className="status-dot" /> Saldos basados en tus movimientos</span><span>Moneda de tu espacio: MXN</span></div></section> : <section className="contacts-grid">{contactsQuery.error && <ErrorNotice error={contactsQuery.error} retry={() => contactsQuery.refetch()} />}{contactsQuery.isPending && <p role="status">Cargando contactos…</p>}{contacts.map(contact => <article className="person-card" key={contact.id}><span className="contact-avatar">{contact.name.slice(0, 1)}</span><h2>{contact.name}</h2><p>{contact.email || "Sin correo registrado"}</p><small>{contact.phone || "Sin teléfono registrado"}</small></article>)}{!contacts.length && !contactsQuery.isPending && <div className="empty-state"><Users size={32} /><h3>Empieza por alguien que conoces.</h3><p>Crea tu primer contacto para registrar un pendiente.</p><button className="secondary" onClick={() => setModal("contact")}>Crear contacto</button></div>}{contactsQuery.hasNextPage && <button className="load-more" onClick={() => contactsQuery.fetchNextPage()}>Cargar más contactos</button>}</section>}
      <footer className="page-footer"><span>Hecho para llevar tus cuentas con calma.</span><span>nomi · Core v0.1</span></footer></div>
    </main>
    {toast && <div className="toast" role="status"><CircleCheck size={18} />{toast}<button aria-label="Cerrar aviso" onClick={() => setToast("")}><X size={16} /></button></div>}
    {modal && <Dialog title={modal === "contact" ? "Un nuevo contacto" : "Registra un pendiente"} onClose={() => setModal(null)}>{modal === "contact" ? <ContactForm onSuccess={contact => { contactCreated(contact); setModal(null); setToast("Contacto guardado."); }} /> : <>{contactsQuery.error && <ErrorNotice error={contactsQuery.error} retry={() => contactsQuery.refetch()} />}<CommitmentForm contacts={contacts} onContact={contactCreated} onSuccess={() => { setModal(null); refresh(); setToast("Tu pendiente ya está en orden."); }} />{contactsQuery.hasNextPage && <button className="text-button" onClick={() => contactsQuery.fetchNextPage()}>Cargar más contactos existentes</button>}</>}</Dialog>}
    {selected && <Detail id={selected} name={names.get(commitments.find(c => c.id === selected)?.contact_id ?? "") ?? "Contacto"} onClose={() => setSelected(null)} onChange={async () => { await refresh(); setToast("Abono registrado. Tu saldo está actualizado."); }} />}
  </div>;
}

function Detail({ id, name, onClose, onChange }: { id: string; name: string; onClose: () => void; onChange: () => Promise<void> }) {
  const [paying, setPaying] = useState(false);
  const detail = useQuery({ queryKey: ["detail", id], queryFn: () => api<Commitment>(`/commitments/${id}`) });
  const history = useInfiniteQuery({ queryKey: ["history", id], initialPageParam: "", queryFn: ({ pageParam }) => api<Page<Transaction>>(`/commitments/${id}/transactions?limit=50${pageParam ? `&cursor=${pageParam}` : ""}`), getNextPageParam: page => page.next_cursor ?? undefined });
  const c = detail.data;
  const movements = history.data?.pages.flatMap(page => page.items).sort((a, b) => a.created_at.localeCompare(b.created_at)) ?? [];
  return <Dialog title={paying ? "Registrar abono" : name} onClose={onClose}>{detail.isPending ? <p role="status">Cargando pendiente…</p> : detail.error ? <ErrorNotice error={detail.error} retry={() => detail.refetch()} /> : c && (paying ? <><button className="text-button" onClick={() => setPaying(false)}>← Volver al historial</button><PaymentForm commitment={c} onRefresh={() => detail.refetch()} onSuccess={async () => { setPaying(false); await onChange(); }} /></> : <><p className="muted">{c.concept || "Tu pendiente"} · {c.direction === "receivable" ? "Me deben" : "Yo debo"}</p><div className="balance-callout"><span>Saldo pendiente</span><strong>{money(c.balance_minor)}</strong></div><div className="detail-facts"><span>Original<strong>{money(c.original_amount_minor)}</strong></span><span>Abonado<strong>{money(c.original_amount_minor - c.balance_minor)}</strong></span><span>Vencimiento<strong>{dateLabel(c.due_date)}</strong></span></div>{c.lifecycle_status === "open" && <button className="primary full" onClick={() => setPaying(true)}><Plus size={17} />Registrar abono</button>}<h3 className="history-title">Así va tu pendiente</h3><ol className="timeline"><li><span className="timeline-dot" /><div><strong>Pendiente creado</strong><small>Monto original</small></div><strong>{money(c.original_amount_minor)}</strong></li>{movements.map(t => <li key={t.id}><span className="timeline-dot green" /><div><strong>{t.type === "payment" ? "Abono registrado" : "Reversión"}</strong><small>{new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Mexico_City" }).format(new Date(t.occurred_at))}</small>{t.note && <small>{t.note}</small>}</div><strong>{t.type === "payment" ? "−" : "+"}{money(t.amount_minor)}</strong></li>)}</ol>{history.error && <ErrorNotice error={history.error} retry={() => history.refetch()} />}{history.hasNextPage && <button className="load-more" onClick={() => history.fetchNextPage()}>Ver más movimientos</button>}</>)}</Dialog>;
}
