from datetime import datetime
from typing import Protocol
from uuid import UUID


class Contacts(Protocol):
    def create(self, workspace_id: UUID, name: str, email, phone, notes=None) -> dict: ...
    def get(self, workspace_id: UUID, contact_id: UUID) -> dict: ...
    def edit(
        self, workspace_id: UUID, contact_id: UUID, expected_updated_at: datetime, changes: dict
    ) -> dict: ...
    def archive(
        self, workspace_id: UUID, contact_id: UUID, expected_updated_at: datetime, archived: bool
    ) -> tuple[dict, bool]: ...
    def require_active(self, workspace_id: UUID, contact_id: UUID) -> None: ...
    def list(self, workspace_id: UUID, cursor, limit: int, status="active", search="") -> dict: ...
    def names(self, workspace_id: UUID, ids) -> dict: ...
    def search_ids(self, workspace_id: UUID, search: str) -> list[UUID]: ...
